# Generated by Django 4.2.16 on 2025-07-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
