# Generated by Django 5.2.6 on 2025-09-14 07:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If True, any registered user can vote. If False, only invited users can vote.'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(help_text='Email address of the person being invited', max_length=254)),
                ('invitation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional personal message with the invitation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='When this invitation expires')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='app.election')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(blank=True, help_text='User being invited (if they have an account)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='election_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Election Invitation',
                'verbose_name_plural': 'Election Invitations',
                'ordering': ['-created_at'],
                'unique_together': {('election', 'invited_email')},
            },
        ),
    ]
