# Generated by Django 4.2.16 on 2025-01-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='public_key',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vote',
            name='encrypted_vote',
            field=models.TextField(default=''),
        ),
    ]
