# Generated by Django 5.2.6 on 2025-09-14 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_election_is_public_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_one_time_link',
            field=models.BooleanField(default=False, help_text='If True, this is a one-time anonymous link that can be used by anyone'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='used_by',
            field=models.ForeignKey(blank=True, help_text='User who used this one-time link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invited_email',
            field=models.EmailField(blank=True, help_text='Email address of the person being invited (optional for one-time links)', max_length=254, null=True),
        ),
    ]
