# Generated by Django 5.2.6 on 2025-09-13 11:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_created_by_to_election'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['election', 'user__last_name', 'user__first_name'], 'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ['-created'], 'verbose_name': 'Election', 'verbose_name_plural': 'Elections'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['name'], 'verbose_name': 'Party', 'verbose_name_plural': 'Parties'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-created'], 'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('user', 'election')},
        ),
    ]
