# Generated by Django 5.2.6 on 2025-09-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_invitation_is_one_time_link_invitation_used_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='When the election was closed', null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the election was activated', null=True),
        ),
    ]
