# Generated by Django 4.2.16 on 2025-01-15 07:57

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_election_private_key_alter_election_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='encrypted_vote',
        ),
        migrations.AlterField(
            model_name='election',
            name='private_key',
            field=encrypted_model_fields.fields.EncryptedCharField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='election',
            name='public_key',
            field=encrypted_model_fields.fields.EncryptedCharField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='ballot',
            field=encrypted_model_fields.fields.EncryptedCharField(default='', editable=False),
        ),
    ]
