# Generated by Django 4.2.16 on 2025-01-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_vote_encrypted_vote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="decrypted_tally",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="election",
            name="encrypted_tally",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
