# Generated by Django 4.2.16 on 2025-01-23 06:44

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_vote_encrypted_vote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='decrypted_total',
            field=encrypted_model_fields.fields.EncryptedCharField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='election',
            name='encrypted_negative_total',
            field=encrypted_model_fields.fields.EncryptedCharField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='election',
            name='encrypted_positive_total',
            field=encrypted_model_fields.fields.EncryptedCharField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='election',
            name='encrypted_zero_sum',
            field=encrypted_model_fields.fields.EncryptedCharField(default='', editable=False),
        ),
    ]
