# Generated by Django 4.2.16 on 2025-01-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_vote_encrypted_vote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='hashed',
            field=models.CharField(default='', editable=False, max_length=128),
        ),
    ]
