# Generated by Django 4.2.16 on 2025-01-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_election_decrypted_total_and_more'),
        ('app', '0005_vote_hashed'),
    ]

    operations = [
    ]
