# Generated by Django 4.2.16 on 2025-01-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_election_decrypted_tally_election_encrypted_tally"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="ballot",
            field=models.JSONField(default=list, editable=False),
        ),
    ]
