# Generated by Django 4.2.16 on 2025-02-03 19:46

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_vote_negative_ballot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='negative_ballot',
        ),
        migrations.AddField(
            model_name='election',
            name='zero_randomness',
            field=encrypted_model_fields.fields.EncryptedCharField(default='', editable=False),
        ),
    ]
