# Generated by Django 4.2.16 on 2025-02-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_election_decrypted_total'),
        ('app', '0008_remove_vote_negative_ballot_election_zero_randomness'),
    ]

    operations = [
    ]
